### ISSUE TITLE
No item for  transparency of menus

### ISSUE THREAD

**Issue by stefonarch** [redtide/picom-conf#1]
##### Expected Behavior

As picom does provide this (default 0.8) there should be a item for it in the setting.
##### Current Behavior

There isn't (anymore), only way is editing `~/.config/picom.conf `manually.
 (btw the issue template needs some adaptions and removals  of lxqt stuff.)

**Comment by redtide** [comment]
Sorry, I haven't noticed the watch settings was off, so I got no notifications for this until now that I opened the project again.
I guess you mean `menu-opacity` (see the [TODO](https://github.com/redtide/picom-conf/wiki/TODO#opacity) in the wiki, at the bottom), which is deprecated and I won't add it for this reason. Unfortunately the replacement for it needs a complex setting (wintype), I'll need some help for this kind of setting and also to how manage the complex new settings in the UI.
For the latter "issue" I'm going to create an "advanced-settings" branch, if you want to build and try/test it. No much changes since I I'm not sure if I can find simpler description for them, at least I can group in an advanced tab section.
I'll give also a look to the issue template.

**Comment by redtide** [comment]
Looking at the issue template the only thing that seems not used is `libqtxdg`, otherwise the tools should be needed to build the translations for the application and desktop files.

The most important thing to me now is to have some feedback to help me to find an appropriated way to display the various options on the UI. Meanwhile I made a little accordion widget hoping it could help to make it easier to access the wintypes options I'm going to add.

**Comment by stefonarch** [comment]
Looks quite fine the new advanced settingslayout.
For the issue template: as it can be useD by any DE it shouldn't report the building dependencies, but maybe version, distro in use ecc.

**Comment by redtide** [comment]
Thank you for testing, I'll add the "Wintypes" accordion based UI today in the same branch, not functional just as preview/WIP if you have time to give it a look.

About issue template: some developer could make a self build and/or having a customized system with different libraries versions (e.g. Debian using PPA). For example by mistake someone could use a LXQt tools version less than 0.8.0, which seems to be the minimum supported/required or having Qt5/6 different issues. Maybe I miss something, otherwise I think I'll remove the kernel version (redundant info?) and `libqtxdg`.

**Comment by redtide** [comment]
If this is fixed I would close it or did I forget something?

**Comment by stefonarch** [comment]
Sure, this is present.
